#!/usr/bin/env python3
"""v34-Embed: mTLS fleet config embed v2 — generates per-repo mTLS YAML configs.

Pillar L52.1 (mTLS fleet). Reads root mtls-config.yaml, generates
per-repo .mtls.yaml files with cert paths, CA bundle, and cipher suites.

Usage:
    python3 tools/mtls-fleet-v2/apply.py --root mtls-config.yaml --out-dir repos/
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

DEFAULT_CONFIG = {
    "cert_dir": "/etc/mtls/certs",
    "ca_bundle": "/etc/mtls/ca.crt",
    "cipher_suites": ["TLS_AES_128_GCM_SHA256", "TLS_AES_256_GCM_SHA384"],
    "min_version": "1.3",
    "repos": ["pheno-port-adapter", "pheno-flags", "pheno-otel", "pheno-errors", "PhenoCompose"],
}


def _load_config(path: Path) -> dict:
    if not path.exists():
        print(f"WARN: {path} not found, using defaults", file=sys.stderr)
        return DEFAULT_CONFIG
    if yaml is None:
        print("WARN: PyYAML not installed, using defaults", file=sys.stderr)
        return DEFAULT_CONFIG
    with open(path) as f:
        return yaml.safe_load(f)


def _generate(repo: str, config: dict) -> str:
    lines = [
        f"# mTLS config for {repo} (auto-generated by v34 embed)",
        f"cert_file: {config['cert_dir']}/{repo}.crt",
        f"key_file: {config['cert_dir']}/{repo}.key",
        f"ca_file: {config['ca_bundle']}",
        f"min_version: {config['min_version']}",
        "cipher_suites:",
    ]
    for suite in config.get("cipher_suites", []):
        lines.append(f"  - {suite}")
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="mTLS fleet config embed v2")
    ap.add_argument("--root", type=Path, default=Path("mtls-config.yaml"),
                    help="Root mTLS config file")
    ap.add_argument("--out-dir", type=Path, default=Path("."),
                    help="Output directory for per-repo configs")
    ap.add_argument("--dry-run", action="store_true",
                    help="Print configs without writing")
    args = ap.parse_args()
    config = _load_config(args.root)
    repos = config.get("repos", DEFAULT_CONFIG["repos"])
    generated = 0
    for repo in repos:
        content = _generate(repo, config)
        out_path = args.out_dir / repo / ".mtls.yaml"
        if args.dry_run:
            print(f"--- {out_path} ---")
            print(content)
        else:
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(content)
            print(f"Written: {out_path}")
        generated += 1
    print(f"Generated {generated} mTLS configs ({'dry-run' if args.dry_run else 'applied'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
